# Stubs for gitdb (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# avoid error introduced by an import clash below
base: Any

from gitdb.base import *
from gitdb.db import *
from gitdb.stream import *
from typing import Any

__contact__: str
__homepage__: str
version_info: Any
