# Stubs for gitdb.const (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

BYTE_SPACE: bytes
NULL_BYTE: bytes
NULL_HEX_SHA: Any
NULL_BIN_SHA: Any
