# Stubs for gitdb.db (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from gitdb.db.base import *
from gitdb.db.loose import *
from gitdb.db.mem import *
from gitdb.db.pack import *
from gitdb.db.git import *
from gitdb.db.ref import *
