# Stubs for gitdb.db.ref (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from gitdb.db.base import CompoundDB
from typing import Any

class ReferenceDB(CompoundDB):
    ObjectDBCls: Any = ...
    def __init__(self, ref_file) -> None: ...
    def update_cache(self, force: bool = ...): ...
