# Stubs for git (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from git.exc import *
from git.objects import *
from git.refs import *
from git.diff import *
from git.db import *
from git.remote import *
from git.index import *
from git.cmd import Git as Git
from git.config import GitConfigParser as GitConfigParser
from git.repo import Repo as Repo
from git.util import Actor as Actor, BlockingLockFile as BlockingLockFile, LockFile as LockFile, Stats as Stats, rmtree as rmtree

# Names in __all__ with no definition:
#   AmbiguousObjectName
#   BadName
#   BadObject
#   BadObjectType
#   BaseIndexEntry
#   Blob
#   BlobFilter
#   CacheError
#   CheckoutError
#   CommandError
#   Commit
#   Diff
#   DiffIndex
#   Diffable
#   FetchInfo
#   GitCmdObjectDB
#   GitCommandError
#   GitCommandNotFound
#   GitDB
#   GitError
#   HEAD
#   Head
#   HookExecutionError
#   IndexEntry
#   IndexFile
#   IndexObject
#   InvalidDBRoot
#   InvalidGitRepositoryError
#   NULL_TREE
#   NoSuchPathError
#   ODBError
#   Object
#   ParseError
#   PushInfo
#   RefLog
#   RefLogEntry
#   Reference
#   Remote
#   RemoteProgress
#   RemoteReference
#   RepositoryDirtyError
#   RootModule
#   RootUpdateProgress
#   Submodule
#   SymbolicReference
#   Tag
#   TagObject
#   TagReference
#   Tree
#   TreeModifier
#   UnicodeMixin
#   UnmergedEntriesError
#   UnsupportedOperation
#   UpdateProgress
#   WorkTreeRepositoryUnsupported
#   absolute_import
#   safe_decode
#   string_types
#   to_hex_sha
