# Stubs for git.refs (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .symbolic import *
from .reference import *
from .head import *
from .tag import *
from .remote import *
from .log import *
