# Stubs for git.refs.remote (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .head import Head
from typing import Any, Optional

class RemoteReference(Head):
    @classmethod
    def iter_items(cls, repo, common_path: Optional[Any] = ..., remote: Optional[Any] = ..., *args, **kwargs): ...
    @classmethod
    def delete(cls, repo, *refs, **kwargs) -> None: ...
    @classmethod
    def create(cls, *args, **kwargs) -> None: ...
