#!/bin/bash

log_prefix='Post-commit hook: '
red_warning='\033[0;91mWARNING\033[0m'

echo "${log_prefix}RUNNING truffleHog to test for leaked secrets."
docker run -t --rm -v "$PWD:/git" mojdigitalstudio/git-secrets-ahoy --use_current_branch --since_commit $(git rev-parse HEAD~1)
exit_code=$?

if [[ $exit_code -ne 0 ]]; then
  echo -e "${log_prefix}${red_warning} truffleHog found some suspicious commits containing possible secrets"
  echo "${log_prefix}You can undo this commit: git reset HEAD~1"
else
  echo "${log_prefix}OK truffleHog did not find anything suspicious"
fi
