#!/bin/bash

log_prefix='Pre-push hook: '
red_warning='\\033[0;91mWARNING\\033[0m'

echo "${log_prefix}RUNNING truffleHog to test for leaked secrets."
docker run -t --rm -v "$PWD:/git" mojdigitalstudio/git-secrets-ahoy --use_current_branch --since_commit $(git rev-parse origin/HEAD)
exit_code=$?

if [[ $exit_code -ne 0 ]]; then
  echo -e "${log_prefix}${red_warning} truffleHog found some suspicious commits containing possible secrets"
  echo "${log_prefix}ABORTING push, to override run: git push --no-verify"
  exit 1
else
  echo "${log_prefix}OK proceeding with push"
  exit 0
fi
