#!/bin/bash

log_prefix='Pre-push hook: '

echo "${log_prefix}RUNNING truffleHog to test for leaked secrets."
docker run -t --rm -v "$PWD:/git" mojdigitalstudio/git-secrets-ahoy --since_commit $(git rev-parse origin/HEAD)
exit_code=$?

if [ $exit_code -ne 0 ]; then
  echo "${log_prefix}WARNING truffleHog found some suspicious commits containing possible secrets\n\n"
  echo "${log_prefix}ABORTING push, to override run: git push --no-verify"
else
  echo "${log_prefix}OK proceeding with push"
fi
