# Stubs for git.objects (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import *
from .blob import *
from .commit import *
from .submodule.base import *
from .submodule.root import *
from .tag import *
from .tree import *
from __future__ import absolute_import as absolute_import

__all__ = [
    "Blob",
    "Commit",
    "IndexObject",
    "Object",
    "RootModule",
    "RootUpdateProgress",
    "Submodule",
    "TagObject",
    "Tree",
    "TreeModifier",
    "UpdateProgress",
]
