# Stubs for gitdb.utils.compat (Python 3.6)
#
# NOTE: This stub was originally generated by stubgen.

from typing import Any, Optional

PY3: Any
izip = zip
xrange = range
def buffer(obj: Any, offset: int, size: Optional[int]) -> Any: ...

def to_bytes(i): ...
MAXSIZE: int
